<a href="https://colab.research.google.com/github/saketh1305/Pytorch_DL/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

In [2]:
import torch
import numpy as np

In [6]:
mylist = [[1,2,3,4,5] , [2,3,4,5,6,]]
mylist

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [10]:
np1 = np.random.rand(3)
np1

array([0.23367011, 0.21559778, 0.09465963])

In [8]:
np1.dtype

dtype('float64')

In [11]:
tensor_2d  = torch.rand(2,3)

In [13]:
tensor_2d

tensor([[0.8045, 0.4509, 0.9861],
        [0.0520, 0.0295, 0.1911]])

In [16]:
tensor_2d.dtype
type(tensor_2d)

torch.Tensor

In [17]:
tensor_3d = torch.zeros(3,4)

In [18]:
tensor_3d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
tensor_np = torch.tensor(np1 , dtype = torch.float32)
print(tensor_np)

tensor([0.2337, 0.2156, 0.0947])


In [23]:
tensor_np.dtype

torch.float32

In [3]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
my_torch2 = torch.arange(25)

In [8]:
my_torch3 = torch.arange(10)

In [11]:
my_torch4 = my_torch2.reshape(5,-1)
my_torch4


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [13]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch7[7]

tensor(7)

In [15]:
my_torch8 = my_torch7.reshape(2,5)

In [17]:
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
torch_slice = my_torch8[:,2:3]

In [27]:
torch_slice

tensor([[2],
        [7]])

In [30]:
torch_slice = torch_slice.squeeze()

In [31]:
torch_slice

tensor([2, 7])

In [32]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [33]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [34]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [35]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [36]:
torch.subtract(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [37]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [38]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [40]:
tensor_b//tensor_a

tensor([5, 3, 2, 2])

In [41]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [43]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
add_